### ISSUE TITLE
Add Digital Ocean to sponors

### ISSUE THREAD

**Issue by imacrayon** [devict/votelocal#102]
We should include the Digital Ocean logo somewhere. In in our list of partners on the homepage or in the footer maybe?

**Comment by sethetter** [comment]
Good idea! Maybe they'll renew our credits then, haha.

**Comment by nightphobos** [comment]
Hi! I didn't see footer on homepage, ad I understand - you want to add DigitalOcean logo to this list on first page?
<img width="778" alt="Снимок экрана 2020-10-03 в 17 50 01" src="https://user-images.githubusercontent.com/4353291/94994553-006dc700-05a1-11eb-80fb-4f4e77ede059.png">
If I understand the issue correctly - can I fix it?

**Comment by nightphobos** [comment]
<img width="793" alt="Снимок экрана 2020-10-03 в 19 38 36" src="https://user-images.githubusercontent.com/4353291/94997149-0a4bf600-05b2-11eb-8f0f-3693032397e9.png">
