### ISSUE TITLE
Modify links on Voting Resources page to open in a new tab

### ISSUE THREAD

**Issue by ph-rudolph** [devict/votelocal#106]
Perhaps we can make the links to voting resource pages open in a new tab instead of redirecting away from votelocalks.org.

People may want to view the other resources or return to the homepage or sign into their subscriber profiles.

Let me know if and how I can be of help. I don't know PHP, but I don't imagine it's a hard fix.

Paul

**Comment by sethetter** [comment]
Done with #117, thanks @aleczzzzz!
