### ISSUE TITLE
Admin calendar view for scheduled messages

### ISSUE THREAD

**Issue by sethetter** [devict/votelocal#49]

**Comment by kentonh** [comment]
@sethetter What's the upward limit of how many messages would be sent on a given day?

**Comment by sethetter** [comment]
There's been plenty of talk about making sure we don't send too many messages and risk unsubscribes, so I would say no more than 1 message x # of active subscribers (right now we're at about 115, but obviously would love to see that number in the thousands).

**Comment by sethetter** [comment]
Wait, for the calendar view, number of subscribers doesn't matter. So yes, I think 1 is typically a max, but I could see there being maybe 3 or so on an actual election day? I think going beyond that might start getting to be too much for people.
