### ISSUE TITLE
Allow messages to go to only specific locales

### ISSUE THREAD

**Issue by sethetter** [devict/votelocal#50]

**Comment by kentonh** [comment]
As a Subscriber, I can enter my location.
As a Sender, I can send or schedule a message to one or many locations.

What designates a location? Zip Code? Do we need an API to (gismaps)[http://gismaps.wichita.gov/Council%20District%20Checker/]?

**Comment by sethetter** [comment]
Locale = language in this case, the discussion was around being able to inform Spanish-speaking subscribers about events specifically for Spanish speaking individuals.

A subscriber's locale currently is controlled by which trigger (subscribe/unsubscribe) word they use, and which locale it's mapped to. If they send one that isn't for the locale they are currently set to, we switch it to the new one.

So texting "Spanish" or "Iniciar" will subsribe/switch you to Spanish, etc.
