### ISSUE TITLE
Rebranding to VoteLocal

### ISSUE THREAD

**Issue by sethetter** [devict/votelocal#91]
With recent updates in #88, the system now has the ability to tag messages for specific locations, and subscribers can choose what locations to receive information for. This allows us to send hyper-local focused content while also expanding the potential geographic relevance of the content.

As part of this effort, we're also rebranding the project as VoteLocal. This will involve a few things, here's the rough high level plan.

1. Turn off the auto deploys from this repo on Heroku.
1. Rename the repo, update references in the codebase, etc.
1. Launch a parallel site at the new domain (couple options available).
1. Load data from old site to new.
1. Point Twilio at the new site.
1. Send out a message letting subscribers know of the changes.

Am I missing anything here?

**Comment by imacrayon** [comment]
Seems good to me. Were you going to put the new site on the Digital Ocean server?

Maybe we should make each of these items an issue and toss them up on a project board?

**Comment by sethetter** [comment]
Since VoteICT is becoming Vote Local, we need a new domain! I've snagged a few, and curious what people's thoughts are on..

1. votelocalks.org
2. ks.votinglocal.org
3. ks.votelocal.in

Other variants on 2 and 3 are also on the table. I also own votelocal.dev, so that's neat. Seeing possible futures where there are instances of this system run by other people in other communities and votelocal.in or votinglocal.org can point to the multiple instances? Idk! I think #1 is the most straightforward, and avoid subdomains, but I think there's more interesting potentials with the other options.

@imacrayon @itsmebennyb thoughts on any of this?

**Comment by jakesuellentrop** [comment]
I'm definitely a fan of the more generic domain, with a locale subdomain

**Comment by sethetter** [comment]
@jakesuellentrop awesome thanks for chiming in! Sorry I didn't tag you in the post >_<

I'm leaning that direction too. I think mostly leaning towards 2, but the name difference is throwing me off.

I just snagged votelocal.io, so ks.votelocal.io is an option! I think that's probably my strongest preference now.

**Comment by imacrayon** [comment]
I'm a fan of the subdomains too. I'm not sure which one I like best though. I know people generally struggle with the newer `.io` & `in` domains. I like the way the `.org` domain reads left-to-right but `voting` instead of `vote` in there could possibly trip people up.

**Comment by jakesuellentrop** [comment]
@sethetter no worries!

I actually looked up votelocal.io, glad you snagged it. The `.org` is obviously more familiar to people than `.io`, but I really like how `votelocal` reads vs `votinglocal`.

**Comment by sethetter** [comment]
What if we go with the name Voting Local instead of Vote Local? Then use votinglocal.org?

**Comment by sethetter** [comment]
Bleh scratch that, I'm not a fan of Voting Local, Vote Local definitely does sound better.

I'm thinking votelocalks.org might be the best bet -- it's the easiest to vocalize, and KMUW will be advertising it on air.

If, in the future, there are other instances of this run in other areas, we could use the `votelocal.in` (or io) domain to host a page pointing to all the different instances. I have `votelocal.dev` too, lol.

Either way, I think this is the way I'm leaning. Any objections?

**Comment by jakesuellentrop** [comment]
I'm on board
